export const SET_CASINO_GAMES = '[APP] SET CASINO GAMES';
export const SET_CASINO_ACTIVE_CATEGORY = '[APP] SET CASINO ACTIVE CATEGORY';
export const SET_CASINO_SEARCH_STARTED = '[APP] SET CASINO SEARCH STARTED';
export const SET_CASINO_SEARCH = '[APP] SET CASINO SEARCH';
export const SET_GAME_DATA = '[APP] SET GAME DATA';
export const CLEAR_CASINO_GAMES = '[APP] CLEAR CASINO GAMES';
export const SET_P_CASINO_GAMES = '[APP] SET P CASINO GAMES';
export const SET_LIVE_CASINO_GAMES = '[APP] SET LIVE CASINO GAMES';
export const SET_LIVE_CASINO_ACTIVE_CATEGORY = '[APP] SET LIVE CASINO ACTIVE CATEGORY';
export const SET_P_CASINO_ACTIVE_CATEGORY = '[APP] SET P CASINO ACTIVE CATEGORY';


export const SET_LIVE_CASINO_SEARCH_STARTED = '[APP] SET LIVE CASINO SEARCH STARTED';
export const SET_LIVE_CASINO_SEARCH = '[APP] SET LIVE CASINO SEARCH';
export const SET_PCASINO_SEARCH = '[APP] SET PCASINO SEARCH';
export const SET_LIVE_GAME_DATA = '[APP] SET LIVE GAME DATA';
export const CLEAR_LIVE_CASINO_GAMES = '[APP] CLEAR LIVE CASINO GAMES';
export const SET_VIRTUAL_SPORTS = '[APP] SET VIRTUAL SPORTS';
export const CLEAR_VIRTUAL_SPORTS = '[APP] CLEAR VIRTUAL SPORTS';
export const SET_VIRTUAL_SPORTS_SEARCH = '[APP] SET VIRTUAL SPORTS SEARCH';
export const SET_VIRTUAL_SPORTS_CATEGORY = '[APP] SET VIRTUAL SPORTS CATEGORY';
export const SET_VIRTUAL_SEARCH_STARTED = '[APP] SET VIRTUAL SEARCH STARTED';
export const SET_CASINO_LOBBY = '[APP] SET CASINO LOBBY';
export const SET_LOADING_SLOT = '[APP] SET_LOADING_SLOT';

export const SET_NEW_CASINO_GAMES = '[APP] SET NEW CASINO GAMES';
export const SET_NEW_CASINO_ACTIVE_CATEGORY = '[APP] SET NEW CASINO ACTIVE CATEGORY';
export const SET_NEW_CASINO_SEARCH_STARTED = '[APP] SET NEW CASINO SEARCH STARTED';
export const SET_NEW_CASINO_SEARCH = '[APP] SET NEW CASINO SEARCH';
export const SET_NEW_GAME_DATA = '[APP] SET NEW GAME DATA';
export const CLEAR_NEW_CASINO_GAMES = '[APP] CLEAR NEW CASINO GAMES';
